apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretsstore
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: "./dapr/components/local_secrets.json"