apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsubdemo
  namespace: daprdemos
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString # Required
    secretKeyRef:
      name: sb-connectionstring
      key:  connectionstring