apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: daprdemos
spec:
  type: state.redis
  version: v1
  metadata:
  - name: actorStateStore
    value: "true"
  - name: redisHost
    value: daprdemos-redis.redis.cache.windows.net:6380
  - name: redisPassword
    secretKeyRef:
      name: redis-password
      key:  password
  - name: enableTLS
    value: true